config/routes.rb
Rails.application.routes.draw do

  resources :breadcrumbs
  devise_for :users

  # BREADCRUMBS
  put 'breadcrumbs/update-paths-nested/:id', to: 'breadcrumbs#update_paths_nested', as: 'update_paths_nested'
  get 'dashboard', to: 'dashboards#index', as: 'dashboard'

	root 'dashboards#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breadcrumb.rb
class Breadcrumb < ApplicationRecord

	# ENUM
	enum status: 
  {
    'Selecione...':        			0,
    'Funcionando':        			1,
    'Apresenta problema':       2
  }

	# MAP
	belongs_to :user_tested, foreign_key: 'user_tested_id', class_name: 'User'
	belongs_to :user_created, foreign_key: 'user_created_id', class_name: 'User'

  has_many :paths, inverse_of: :breadcrumb
  accepts_nested_attributes_for :paths, reject_if: :all_blank, allow_destroy: true

	# VALIDATIONS
	validates_presence_of :name, length: { maximum: 255 }
	validates :code, uniqueness: true, length: { maximum: 6 }

end

app/models/path.rb
class Path < ApplicationRecord
  
  belongs_to :breadcrumb

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :breadcrumbs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  def user_not_authorized
    flash[:alert] = "Você não está autorizado a acessar isso."
    redirect_to(request.referrer || root_path)
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, 
      :password, :password_confirmation, :full_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :password, 
      :password_confirmation, :full_name])
  end  

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

end

app/controllers/breadcrumbs_controller.rb
class BreadcrumbsController < ApplicationController
  before_action :set_breadcrumb, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /breadcrumbs
  # GET /breadcrumbs.json
  def index
    @breadcrumbs = Breadcrumb.all
  end

  # GET /breadcrumbs/1
  # GET /breadcrumbs/1.json
  def show
  end

  # GET /breadcrumbs/new
  def new
    @breadcrumb = Breadcrumb.new
  end

  # GET /breadcrumbs/1/edit
  def edit
    authorize @breadcrumb
  end

  # POST /breadcrumbs
  # POST /breadcrumbs.json
  def create
    @breadcrumb = Breadcrumb.new(breadcrumb_params.merge(user_created_id: current_user.id))

    respond_to do |format|
      if @breadcrumb.save
        format.html { redirect_to breadcrumbs_url, notice: I18n.t(:new, scope: [:generic, :confirmation]) }
        format.json { render :show, status: :created, location: @breadcrumb }
      else
        format.html { render :new }
        format.json { render json: @breadcrumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breadcrumbs/1
  # PATCH/PUT /breadcrumbs/1.json
  def update
    authorize @breadcrumb

    respond_to do |format|
      if @breadcrumb.update(breadcrumb_params)
        format.html { redirect_to breadcrumbs_url, notice: I18n.t(:edit, scope: [:generic, :confirmation]) }
        format.json { render :show, status: :ok, location: @breadcrumb }
      else
        format.html { render :edit }
        format.json { render json: @breadcrumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breadcrumbs/1
  # DELETE /breadcrumbs/1.json
  def destroy
    authorize @breadcrumb

    @breadcrumb.destroy
    respond_to do |format|
      format.html { redirect_to breadcrumbs_url, notice: I18n.t(:delete, scope: [:generic, :confirmation]) }
      format.json { head :no_content }
    end
  end

  # CUSTOM METHODS

  def update_paths_nested
    @path = Path.find(params[:id])
    if @path.update(path_params)
    respond_to do |format|
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breadcrumb
      @breadcrumb = Breadcrumb.find(params[:id])
    end

    def path_params
      params.require(:path).permit(:status, :description, :observation)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breadcrumb_params
      params.require(:breadcrumb).permit(
        :name,
        :description,
        :code,
        :progress,
        :user_created_id,
        :user_tested_id,
        :status,
        :observation,
        paths_attributes: [
          :id,
          :description,
          :status,
          :observation, 
          :_destroy
        ]
      )
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @total_breadcrumb = Breadcrumb.count
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breadcrumbs_helper.rb
module BreadcrumbsHelper
end

app/views/breadcrumbs/_form.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="header">
          <h4 class="title">Informações operacionais</h4>
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <%= simple_form_for(@breadcrumb) do |f| %>
              
              <%= f.error_notification %>

              <div class="form-inputs">
                <div class="form-group">
                  <%= f.input :code, label: 'Código' %>
                </div>
              </div>

              <div class="form-inputs">
                <div class="form-group">
                  <%= f.input :name, label: 'Nome' %>
                </div>
              </div>

              <div class="form-inputs">
                <div class="form-group">
                  <%= f.input :description, label: 'Descrição' %>
                </div>
              </div>

              <div class="form-inputs">
                <div class="form-group">
                  <%= f.association :user_tested, label: 'Usuário que irá testar', label_method: :full_name %>
                </div>
              </div>

              <h4 class="title">Informações sobre os caminhos</h4>
              <br />

              <div id="paths">
                <%= f.simple_fields_for :paths do |path| %>
                  <%=render 'path_fields', f: path %>
                <% end %>
                <div class="links">
                  <div class="pull-left">
                    <%=link_to_add_association "<div class='btn btn-info btn-fill btn-wd btn-xs'>Adicionar Caminho</div>".html_safe, f, :paths %>
                  </div>
                </div>
              </div>

              <br />
              <hr />
              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-actions">
                    <div class="pull-left">
                      <%= f.button :submit, 'Novo Registro' %>
                    </div>
                    <div class="pull-right">
                      <%= link_to 'Voltar', breadcrumbs_path , class: 'btn btn-dark' %>
                    </div>
                  </div>
                </div>
              </div>

            <% end %>
          </div>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/breadcrumbs/_path_fields.html.erb
<div class="nested-fields">
  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :description, label: 'Descrição' %>
    </div>
  </div>
  <div class="pull-right">
  	<%= link_to_remove_association "<div class='btn btn-danger btn-fill btn-wd btn-xs'>Remover Caminho</div>".html_safe, f %>
  </div>
</div>
<br />

app/views/breadcrumbs/edit.html.erb
<%= render 'shared/settings' , path_name: 'Caminhos/Editar' %>
<%= render 'form', breadcrumb: @breadcrumb %>

app/views/breadcrumbs/index.html.erb
<%= render 'shared/settings' , path_name: 'Caminhos' %>
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="header">
          <h4 class="title">Lista de caminhos</h4>
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="content table-responsive table-full-width">
              <table id="datatable" class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Data</th>
                    <th>Criado por</th>
                    <th>Testado por</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Progresso</th>
                    <th style="width:100px">Ações</th>
                  </tr>
                </thead>

                <tbody>
                  <% @breadcrumbs.each do |breadcrumb| %>
                    <tr>
                      <td><%= breadcrumb.code %></td>
                      <td><%= l breadcrumb.created_at, format: :short %></td>
                      <td><%= breadcrumb.user_created.full_name %></td>
                      <td><%= breadcrumb.user_tested.full_name %></td>
                      <td><%= breadcrumb.name %></td>
                      <td><%= breadcrumb.description %></td>
                      <td>
                        <% 
                          @working = breadcrumb.paths.where(status: 2).count
                          @total = breadcrumb.paths.count
                        %>
                        <strong>Total:</strong> <%=@total%>
                        <br />
                        <strong>Funcionando:</strong> <%=@working%>
                      </td>
                      <td>
                        <%= link_to '<btn class="btn btn-xs btn-default btn-icon"><i class="fa fa-eye"></i></btn>'.html_safe, breadcrumb %>
                        <% if current_user.id == breadcrumb.user_created_id %>
                          <%= link_to '<btn class="btn btn-xs btn-success btn-icon"><i class="fa fa-pencil"></i></btn>'.html_safe, edit_breadcrumb_path(breadcrumb) %>  
                          <%= link_to '<btn class="btn btn-xs btn-danger btn-icon"><i class="fa fa-trash"></i></btn>'.html_safe, breadcrumb, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <hr />
            <%= link_to 'Novo registro', new_breadcrumb_path , class: 'btn btn-dark' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/flash', flash: flash %>

app/views/breadcrumbs/new.html.erb
<%= render 'shared/settings' , path_name: 'Caminhos/Cadastrar' %>
<%= render 'form', breadcrumb: @breadcrumb %>

app/views/breadcrumbs/show.html.erb
<%= render 'shared/settings' , path_name: 'Caminhos/Visualizar' %>
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="content">
        <div class="pull-right">
          <%= link_to 'Voltar', breadcrumbs_path , class: 'btn btn-dark' , :"data-turbolinks" => false %>
        </div>
      </div>
      <div class="header">
          <h4 class="title"><%=@breadcrumb.name%></h4>
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-4">
            <strong>Criado por:</strong>
            <br />
            <%=@breadcrumb.user_created.full_name %>
          </div>
          <div class="col-md-4">
            <strong>Testado por:</strong>
            <br />
            <%=@breadcrumb.user_tested.full_name %>
          </div>
          <div class="col-md-4">
            <h3 style="margin-top:0; text-align: center">Happiness path?</h3>
            <br />
            <center>
              <% 
                @working = @breadcrumb.paths.where(status: 2).count
                @total = @breadcrumb.paths.count
              %>
              <% if @working == @total %>
                <%=image_tag('ok.png')%>
              <% else @working != @total %>  
                <%=image_tag('fail.png')%>
              <% end %>
            </center>
          </div>
          <div class="col-md-12">
            <strong>Descrição:</strong>
            <br />
            <%=@breadcrumb.name%>
          </div>
        </div>
      </div>
      <hr />
      <div class="content">
        <div class="row">
          <div class="header" style="padding-top: 0">
              <h4 class="title" style="margin: 0">Caminho</h4>
          </div>
          <hr />
          <div class="col-md-12">
            <% @breadcrumb.paths.each do |path| %>
              <div class='row'>
                <div class="col-md-9">
                  <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><strong>Descrição:</strong>
                  <br />
                  <%=path.description %>
                </div>
                <div class="col-md-3">
                  <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><strong>Status:</strong>
                  <br />
                  <%= best_in_place path, :status, as: :select, url: update_paths_nested_path(path), html_attrs: {class: 'form-control string best_in_place'}, collection: Breadcrumb.statuses.keys
                     %>
                </div>
                <div class="col-md-12">
                  <i class="fa fa-arrow-circle-right" aria-hidden="true"></i><strong>Observação:</strong>
                  <br />
                  <%= best_in_place path, :observation, as: :input, url: update_paths_nested_url(path), html_attrs: {class: 'form-control string best_in_place'}
                     %>
                </div>
              </div>
              <hr />
            <% end %>
          </div>
          <div class="content">
            <div class="pull-right">
              <%= link_to 'Voltar', breadcrumbs_path , class: 'btn btn-dark' , :"data-turbolinks" => false %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<%= render 'shared/settings' , path_name: 'Bem vindo!' %>
<div class="content">
  <div class="container-fluid">
    <div class="content">
      <div class="row">
        <div class="col-md-12" style="text-align: center">
          <h3>Olá seja bem vindo <strong><%=current_user.full_name %></strong>. 
          <hr />
          Atualmente nós temos um total de <strong><%=@total_breadcrumb %></strong> de caminhos</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/flash', flash: flash %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>John and Mary</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--     Fonts and icons     -->
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  </head>

  <body>
  	<div class="wrapper">
  		<%= render "shared/menu" %>
    	<div class="main-panel">
    		<%= yield %>
        <%= render "shared/footer" %>
    	</div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!doctype html>
<html>
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/img/favicon.png">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>John and Mary - Bem vindo</title>

  <style>
  .colorgraph {
    height: 5px;
    border-top: 0;
    background: #c4e17f;
    border-radius: 5px;
    background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
    background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  }    
  </style>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>

  </head>

  <body>
  	<div class="wrapper">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<script>
		$.notify({
			message: "<%= notice %>"
		},{
			type: 'success'
		});
	</script>
  </div>
<% end %>

<% if flash[:alert] %>
	<script>
		$.notify({
			message: "<%= notice %>"
		},{
			type: 'danger'
		});
	</script>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="http://www.prosas.com.br">
                        Prosas
                    </a>
                </li>
            </ul>
        </nav>
		<div class="copyright pull-right">
            Desenvolvido por Mário Augusto Carvalho
        </div>
    </div>
</footer>

app/views/shared/_menu.html.erb
<div class="sidebar" data-background-color="white" data-active-color="danger">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="<%=dashboard_path%>" class="simple-text">
                <strong>Prosas</strong> Quality Control
            </a>
        </div>

        <ul class="nav">
            <li>
                <%= link_to '<i class="fa fa-television" aria-hidden="true"></i> <p>Dashboard</p>'.html_safe, dashboard_path, :"data-turbolinks" => false %>
            </li>
            <li>
                <%= link_to '<i class="fa fa-bicycle" aria-hidden="true"></i> <p>Caminhos</p>'.html_safe, breadcrumbs_path, :"data-turbolinks" => false %>
            </li>
            <hr />
            <li>
                <%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> <p>Sair</p>'.html_safe, destroy_user_session_path, method: :delete %>
            </li>
        </ul>
    </div>
</div>

app/views/shared/_settings.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a class="navbar-brand" href="#"><%=path_name%></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                        <i class="fa fa-user" aria-hidden="true" style="color:#1f51a3"></i>
                        <p>Olá, <%=current_user.full_name%></p>
                    </a>
                </li>
                <li>
                    <a href="<%=edit_user_registration_path%>">
                        <i class="fa fa-cog" aria-hidden="true"></i>
                        <p>Configurações</p>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>